### PR TITLE
CORTX-33117 : Adding copy-object API test cases to nightly s3-tests ceph & splunk test suite job

### PR DESCRIPTION
**Pull request by priyanka25081999**
# Problem Statement
- CORTX-33117 : Adding copy-object API test cases to nightly s3-tests ceph & splunk test suite job

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
- [x] Jenkins pipelines used for testing - Splunk - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Splunk-RGW/164/ 
Ceph - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Ceph-RGW/210/

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by priyanka25081999** [comment]
@cdeshmukh @kapiljinna @sachitanands @shraddhaghatol @shriya-deshmukh Please review this PR. This enables copy-object test cases.

**Comment by priyanka25081999** [comment]
Splunk job - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Splunk-RGW/160/ [PASSED]
Ceph job - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Ceph-RGW/206/ [UNSTABLE - The failed cases of Ceph job are known]

**Comment by cdeshmukh** [comment]
image
image

**Review by cdeshmukh — DISMISSED** [review]

**Review by sachitanands — APPROVED** [review]
looks good.

About known failure test case in ceph job, they will be removed as a part of https://github.com/Seagate/cortx-re/pull/1179

**Comment by kapiljinna** [comment]
Reviewed . Looks good.

**Comment by priyanka25081999** [comment]
Added one more copy-object test case (copy-object zero size tests) and Re-triggered the Splunk job - 
https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Splunk-RGW/164/ [**PASSED**]
image

**Comment by priyanka25081999** [comment]
Added one more copy-object test case (copy-object zero size tests) and Re-triggered the **Ceph** job - (https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Ceph-RGW/210/) [**UNSTABLE**]

image

**Comment by priyanka25081999** [comment]
Ceph Job is unstable again - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Ceph-RGW/210/

There are following failure tests
[s3tests_boto3.functional.test_s3.test_get_object_ifnonematch_good]
[s3tests_boto3.functional.test_s3.test_get_object_ifmodifiedsince_failed]
[s3tests_boto3.functional.test_s3.test_multipart_copy_improper_range]
[s3tests_boto3.functional.test_s3.test_get_object_ifnonematch_good]
[s3tests_boto3.functional.test_s3.test_get_object_ifmodifiedsince_failed]
[s3tests_boto3.functional.test_s3.test_multipart_copy_improper_range]

All above failure tests are known. Hence we can safely merge this PR.

**Review by cdeshmukh — APPROVED** [review]

**Review by sachitanands — DISMISSED** [review]

**Comment by priyanka25081999** [comment]
@shailesh-vaidya @gauravchaudhari02 changes are ready for merger, but I am seeing one of the PR check (cla-signed) is failing. Could you please suggest how to fix it ?
If it's okay to ignore then can we merge this PR. 
cc: @cdeshmukh @sachitanands

**Comment by shailesh-vaidya** [comment]
> @shailesh-vaidya @gauravchaudhari02 changes are ready for merger, but I am seeing one of the PR check (cla-signed) is failing. Could you please suggest how to fix it ? If it's okay to ignore then can we merge this PR. cc: @cdeshmukh @sachitanands

@mukul-seagate11 , @pankajgborole  - Can you please check this issue.

**Review by shailesh-vaidya — DISMISSED** [review]

**Review by sachitanands — APPROVED** [review]

**Review by cdeshmukh — APPROVED** [review]

**Review by shriya-deshmukh — APPROVED** [review]

**Review by kapiljinna — APPROVED** [review]

**Review by shraddhaghatol — APPROVED** [review]

**Comment by mukul-seagate11** [comment]
> > @shailesh-vaidya @gauravchaudhari02 changes are ready for merger, but I am seeing one of the PR check (cla-signed) is failing. Could you please suggest how to fix it ? If it's okay to ignore then can we merge this PR. cc: @cdeshmukh @sachitanands
> 
> @mukul-seagate11 , @pankajgborole - Can you please check this issue.

@shailesh-vaidya, added Priyanka to the cla list

CC @priyanka25081999, update your local branch otherwise cla check will be good in next PR

**Comment by priyanka25081999** [comment]
> > > @shailesh-vaidya @gauravchaudhari02 changes are ready for merger, but I am seeing one of the PR check (cla-signed) is failing. Could you please suggest how to fix it ? If it's okay to ignore then can we merge this PR. cc: @cdeshmukh @sachitanands
> > 
> > 
> > @mukul-seagate11 , @pankajgborole - Can you please check this issue.
> 
> @shailesh-vaidya, added Priyanka to the cla list
> 
> CC @priyanka25081999, update your local branch otherwise cla check will be good in next PR

Thanks @mukul-seagate11

**Comment by priyanka25081999** [comment]
Raised another draft PR to verify cla-signed check - https://github.com/Seagate/cortx-re/pull/1188 [**PASSED**]
Added more details and screenshot in JIRA - https://jts.seagate.com/browse/CORTX-34040

**Comment by priyanka25081999** [comment]
Hi @shailesh-vaidya 
We are good to merge this PR.

**Comment by shailesh-vaidya** [comment]
> Hi @shailesh-vaidya We are good to merge this PR.

@priyanka25081999 Please update PR Template details at - https://github.com/Seagate/cortx-re/pull/1180#issue-1344048594

**Comment by priyanka25081999** [comment]
> > Hi @shailesh-vaidya We are good to merge this PR.
> 
> @priyanka25081999 Please update PR Template details at - [#1180 (comment)](https://github.com/Seagate/cortx-re/pull/1180#issue-1344048594)

Hi @shailesh-vaidya 
Updated the PR template details. Please review.

**Review by shailesh-vaidya — APPROVED** [review]

**Pull request merged**
