### PR TITLE
CORTX-34078: Install xmlstarlet for cortx-rgw build process

### PR DESCRIPTION
**Pull request by shailesh-vaidya**
# Problem Statement
- `xmlstarlet ` package is not available through EPEL repo for cortx-rgw repo. Added package in local repo. 

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
- [x] Jenkins pipelines used for testing - https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/7700/parameters/

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Review by pankajgborole — DISMISSED** [review]
Approved

**Review by pankajgborole — DISMISSED** [review]
Approved

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Review by mukul-seagate11 — APPROVED** [review]
.

**Pull request merged**
