### PR TITLE
CORTX-28628 - Remove python3-ldap package from cortx-rgw image

### PR DESCRIPTION
**Pull request by subhalaxmisa**
# Problem Statement
Remove python3-ldap package from cortx-rgw image

### Specification of requested package

Details | Values
------ | ------
Package Name  |  python3-ldap
Version | 3.3.1-2.el8
license |
Source  | 
Component Team |

### Please add below details about package

* [ ] Purpose of using new SW ?  - Used for LDAP authentication which is no longer needed. 
* [ ] Location of the source code of new opensource SW ?
* [ ] Did you evaluate existing SW and confirm they do not serve the purpose ? If yes, include the comparison. If no, why ? 
* [ ] Who is building it or how it gets built ? If yes, Which component/rpm will it be included ? i.e. name of the rpm which includes SW.
* [ ] Download location of opensource software package ? python3-ldap package is removed from rgw image
* [ ] Who will be supporting this package ? 
* [ ] Is there a configuration required for this? Who will be configuring it ? No
* [ ] Which component is responsible for deploying on nodes ? RGW
* [ ] What is the licensing policy ? Is it approved by legal ? No
* [ ] Are we modifying the software or just using it as-is? No
* [ ] How are we interfacing with this software? (e.g. command-line, static link, python import, dynamic link, etc) No, 3N and IN deployment is working as expected

### CODE REVIEW

**Review by shailesh-vaidya — CHANGES_REQUESTED** [review]
- Please use this template https://github.com/Seagate/cortx-re/blob/main/.github/PULL_REQUEST_TEMPLATE/cortx-prereq-template.md 
- Please validate the build and deployment with this change.

**Comment by subhalaxmisa** [comment]
@shailesh-vaidya 
- Images created : Jenkins Job : [GitHub-custom-ci-builds » generic » custom-ci #6543 Console [Jenkins] (seagate.com)](https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6543/console)

cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-6543-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-6543-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-6543-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-6543-custom-ci

- Deployment passed successfully: [Cortx-Automation » RGW » setup-cortx-rgw-cluster #6307 Console [Jenkins] (seagate.com)](https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/6307/console)

**Comment by shailesh-vaidya** [comment]
@subhalaxmisa - 3N deployment is also working 

image

**Comment by shailesh-vaidya** [comment]
@johnbent, @ujjwalpl, @cdeshmukh  - This PR is to **remove** python3-ldap package from cortx-rgw image as it's not required anymore. We have validated 1N and 3N deployment with changes. Refer to https://github.com/Seagate/cortx-re/pull/1059#issuecomment-1149563545 and https://github.com/Seagate/cortx-re/pull/1059#issuecomment-1149506931

Please review and approve this PR.

**Review by gauravchaudhari02 — APPROVED** [review]

**Review by cdeshmukh — APPROVED** [review]

**Review by ujjwalpl — APPROVED** [review]

**Review by johnbent — APPROVED** [review]
lgtm

**Review by shailesh-vaidya — APPROVED** [review]

**Pull request merged**
