### PR TITLE
EOS-27287 cortx-all image - Remove kafka from cortx-all image

### PR DESCRIPTION
**Pull request by shailesh-vaidya**
# Problem Statement
- Remove kafka from cortx-all image

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [x] Test Cases cover Happy Path, Non-Happy Path and Scalability -
   Generated custom-image as `cortx-docker.colo.seagate.com/seagate/cortx-all:kafka-removed-758` and tested single-node deployment using http://eos-jenkins.colo.seagate.com/job/Cortx-kubernetes/job/setup-cortx-cluster/1076/ 
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Review by sachinpunadikar — APPROVED** [review]
+1

**Review by gauravchaudhari02 — APPROVED** [review]

**Review by ujjwalpl — APPROVED** [review]

**Comment by shailesh-vaidya** [comment]
@johnbent  - Could you please approve this PR to remove Kafka rpm from cortx-all image.

**Review by johnbent — APPROVED** [review]

**Comment by johnbent** [comment]
Approved! But I do want to point out that @mbcortx is still currently planning to use kafka for the replication work.

**Comment by mbcortx** [comment]
We used kafka to accelerate our efforts to complete PI-5 items on time, as a backup strategy for FDMI ack/release mechanism, while waiting FDMI to become more stable and solid. Removing kafka should not affect us at this point, since we switched to RGW, and we need to do a fresh design if needed.

**Review by mbcortx — APPROVED** [review]

**Pull request merged**
