### PR TITLE
CORTX-29737: logrotate rpm is not available in cortx-data pod of corx…

### PR DESCRIPTION
**Pull request by atulsdeshmukh2312**
logrotate rpm is not available in cortx-data pod of cortx-data docker image

Signed-off-by: Atul Deshmukh <atul.deshmukh@seagate.com>

### Specification of requested package

Details | Values
------ | ------
Package Name  | logrotate 
Version | 3.14.0-4.el8.x86_64
license | GPLv2+
Source  | https://vault.centos.org/8.5.2111/BaseOS/Source/SPackages/logrotate-3.14.0-4.el8.src.rpm 

### Please add below details about package

* [x] Purpose of using new SW ?
       To rotate motr logs. 
* [x] Location of the source code of new opensource SW ?
       https://vault.centos.org/8.5.2111/BaseOS/Source/SPackages/logrotate-3.14.0-4.el8.src.rpm
* [x] Did you evaluate existing SW and confirm they do not serve the purpose ? If yes, include the comparison. If no, why ?
       logrotate rpm is needed to rotate the logs which is not available in current data pod.
* [x] Who is building it or how it gets built ? If yes, Which component/rpm will it be included ? i.e. name of the rpm which includes SW.
       RE team builds the library and creates RPM from the source
* [x] Download location of opensource software package ?
       https://vault.centos.org/8.5.2111/BaseOS/Source/SPackages/logrotate-3.14.0-4.el8.src.rpm
* [x] Who will be supporting this package ?
       Linux distribution e.g. centos
* [x] Is there a configuration required for this? Who will be configuring it ?
       No
* [x] Which component is responsible for deploying on nodes ?
       DevOps (RE)
* [x] What is the licensing policy ? Is it approved by legal ? 
       GPLv2+.  It is Legal.

### CODE REVIEW

**Comment by shailesh-vaidya** [comment]
@ujjwalpl @johnbent - Could you please review this request

**Comment by shailesh-vaidya** [comment]
@ujjwalpl , @johnbent  - Could you please review and approve this PR.

**Review by ujjwalpl — APPROVED** [review]

**Review by johnbent — APPROVED** [review]

**Review by shailesh-vaidya — APPROVED** [review]

**Comment by johnbent** [comment]
We cannot merge this. We cannot use GPL software because it is viral copyleft.

**Review by johnbent — COMMENTED** [review]
We cannot use GPLv2 licensed software. Also, where was it discussed to add this new SW dependency?

**Comment by johnbent** [comment]
Also, @ujjwalpl and @shailesh-vaidya , I'm confused that we would need to install an RPM for this. logrotate is included in Linux by default so can't we just use the already installed logrotate instead of installing something ourselves?

image

**Comment by johnbent** [comment]
If we are only calling it using the command line, then it is OK. If there is a header file and a programmatic way to use it, we have to avoid that. But command line invocation is fine. @atulsdeshmukh2312 , can you confirm how we are interacting with it please?

**Pull request merged**
