### PR TITLE
CORTX-28838 : Add image details in auto jira comment

### PR DESCRIPTION
**Pull request by gauravchaudhari02**
Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@seagate.com>

# Problem Statement
- Image information was missing in auto comment in JIRA tickets.

# Design
-  Add image information in comment code section 

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Review by shailesh-vaidya — COMMENTED** [review]
Please use `cortx_images` and print all CORTX images. e.g. CORTX-ALL, CORTX-RGW, etc.

**Review by shailesh-vaidya — CHANGES_REQUESTED** [review]
Please fix the Codacy issue.
Please test with a dummy Jira ticket and add details to PR.

**Comment by gauravchaudhari02** [comment]
> Please fix the Codacy issue. Please test with a dummy Jira ticket and add details to PR.

Tested auto jira comment with dummy data
image

**Comment by shailesh-vaidya** [comment]
> > Please fix the Codacy issue. Please test with a dummy Jira ticket and add details to PR.
> 
> Tested auto jira comment with dummy data image

@gauravchaudhari02 - We should add image details like below so Developer and QA will know which image to be used to test this issue. 
```
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5176-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5176-custom-ci
```

**Review by shailesh-vaidya — APPROVED** [review]

**Pull request merged**
