### PR TITLE
CORTX-34145: Update cortx-k8s version to v0.12.0

### PR DESCRIPTION
**Pull request by gauravchaudhari02**
Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@seagate.com>

# Problem Statement
- K8s repository version changed to v0.12.0

# Design
-  Added support for cortx-k8s v0.12.0 in RE repo

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [x] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
- [x] Jenkins pipelines used for testing  - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/12136/

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

-----
[View rendered solutions/community-deploy/CORTX-Deployment.md](https://github.com/gauravchaudhari02/cortx-re/blob/v0.12.0/solutions/community-deploy/CORTX-Deployment.md)

### CODE REVIEW

**Comment by gauravchaudhari02** [comment]
Deployment with Sanity/Regression has passed for changes
image

**Review by pankajgborole — APPROVED** [review]
Approved changes. 
With v0.12.0 deployment with 1N, 3N and nightly  5N worked fine. Sanity/regression completed without any issues.

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by mukul-seagate11** [comment]
update new job link as tested with v0.12.0

**Comment by gauravchaudhari02** [comment]
> update new job link as tested with v0.12.0

https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/12213/

**Pull request merged**
