### PR TITLE
CORTX-30265 - paramiko package upgrade to 2.10.4

### PR DESCRIPTION
**Pull request by swanand-gadre**
### Specification of requested package

Details | Values
------ | ------
Package Name  | paramiko
Version | 2.10.4
license | GNU Library or Lesser General Public License (LGPL) (LGPL)
Source  | https://github.com/paramiko/paramiko

### Please add below details about package

* [X] Purpose of using new SW ? This is upgrade paramiko library from version 2.7.X to 2.10.4
* [X] Location of the source code of new opensource SW ? https://github.com/paramiko/paramiko
* [X] Did you evaluate existing SW and confirm they do not serve the purpose ? If yes, include the comparison. If no, why ?
**Yes, all the test results are uploaded in a document. This document is attached to *https://jts.seagate.com/browse/CORTX-30265*
* [X] Who is building it or how it gets built ? If yes, Which component/rpm will it be included ? i.e. name of the rpm which includes SW.
wheel file is downloaded from https://pypi.org/project/paramiko/2.10.4/#files
* [X] Download location of opensource software package ?
https://pypi.org/project/paramiko/2.10.4/#files
* [X] Who will be supporting this package ?
opensource community
* [X] Is there a configuration required for this? Who will be configuring it ?
No configuration required
* [X] Which component is responsible for deploying on nodes ?
cortx-re is responsible for deployment
* [X] What is the licensing policy ? Is it approved by legal ? 
GNU Library or Lesser General Public License (LGPL) (LGPL)
This library is upgrade from version 2.7.X to 2.10.4
* [X] Are we modifying the software or just using it as-is?
We are using it "as-is"
* [X] How are we interfacing with this software? (e.g. command-line, static link, python import, dynamic link, etc)
* python import

### CODE REVIEW

**Comment by swanand-gadre** [comment]
**Please approve only.
Do not merge this PR.**

**Review by shailesh-vaidya — COMMENTED** [review]
@swanand-gadre  - Can you please use the updated PR template from https://github.com/Seagate/cortx-re/blob/main/.github/PULL_REQUEST_TEMPLATE/cortx-prereq-template.md

**Comment by swanand-gadre** [comment]
Hi @shailesh-vaidya 

I updated description as per the template.

Regard
Swanand

**Review by ujjwalpl — APPROVED** [review]

**Comment by johnbent** [comment]
LGTM

**Review by johnbent — APPROVED** [review]
LGTM

**Review by shailesh-vaidya — APPROVED** [review]

**Review by gauravchaudhari02 — APPROVED** [review]

**Pull request merged**
