### PR TITLE
CORTX-33719: Modification to Configurable AWS EBS volumes.

### PR DESCRIPTION
**Pull request by nitisdev**
Signed-off-by: Nitish Singh <nitish.singh@seagate.com>

# Problem Statement
- Modification to Configurable AWS EBS volumes.

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design
1. Modify ebs volumes count & size.

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [x] Unit and System Tests are added
- [x] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [x] Testing was performed with RPM
- [x] Jenkins pipelines used for testing

1. Job: 

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [x] Interface change (if any) are documented
- [x] Side effects on other features (deployment/upgrade)
- [x] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [x] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by mukul-seagate11** [comment]
@nitisdev, variables defined has not been declared in main.tf as per error so please fix as,

`MyTestLabVM> terraform validate
╷
│ Error: Reference to undeclared input variable
│
│   on main.tf line 45, in locals:
│   45:   ec2_device_names_to_attach = slice(var.ec2_device_names, 0, var.ebs_volume_count)
│
│ An input variable with the name "ec2_device_names" has not been declared. This variable can be declared
│ with a variable "ec2_device_names" {} block.
╵
╷
│ Error: Reference to undeclared input variable
│
│   on main.tf line 161, in resource "aws_ebs_volume" "data_vol":
│  161:   size              = var.ebs_volume_size
│
│ An input variable with the name "ebs_volume_size" has not been declared. This variable can be declared
│ with a variable "ebs_volume_size" {} block.
`

**Comment by nitisdev** [comment]
> @nitisdev, variables defined has not been declared in main.tf as per error so please fix as,
> 
> > terraform validate
> > ╷
> > │ Error: Reference to undeclared input variable
> > │
> > │   on main.tf line 45, in locals:
> > │   45:   ec2_device_names_to_attach = slice(var.ec2_device_names, 0, var.ebs_volume_count)
> > │
> > │ An input variable with the name "ec2_device_names" has not been declared. This variable can be declared
> > │ with a variable "ec2_device_names" {} block.
> > ╵
> > ╷
> > │ Error: Reference to undeclared input variable
> > │
> > │   on main.tf line 161, in resource "aws_ebs_volume" "data_vol":
> > │  161:   size              = var.ebs_volume_size
> > │
> > │ An input variable with the name "ebs_volume_size" has not been declared. This variable can be declared
> > │ with a variable "ebs_volume_size" {} block.

@mukul-seagate11 - Please  copy variable.tf & user.tfvars along wiht main.tf file also. Variables declaration have been moved to varaible.tf file from main.tf.
I validated with same:
image

**Comment by mukul-seagate11** [comment]
> > @nitisdev, variables defined has not been declared in main.tf as per error so please fix as,
> > > terraform validate
> > > ╷
> > > │ Error: Reference to undeclared input variable
> > > │
> > > │   on main.tf line 45, in locals:
> > > │   45:   ec2_device_names_to_attach = slice(var.ec2_device_names, 0, var.ebs_volume_count)
> > > │
> > > │ An input variable with the name "ec2_device_names" has not been declared. This variable can be declared
> > > │ with a variable "ec2_device_names" {} block.
> > > ╵
> > > ╷
> > > │ Error: Reference to undeclared input variable
> > > │
> > > │   on main.tf line 161, in resource "aws_ebs_volume" "data_vol":
> > > │  161:   size              = var.ebs_volume_size
> > > │
> > > │ An input variable with the name "ebs_volume_size" has not been declared. This variable can be declared
> > > │ with a variable "ebs_volume_size" {} block.
> 
> @mukul-seagate11 - Please copy variable.tf & user.tfvars along with main.tf file also. Variables declaration have been moved to varaible.tf file from main.tf. I validated with same: image

yes re-tested so its validated & working fine

**Review by mukul-seagate11 — APPROVED** [review]
looks good as per validated,

> terraform validate && terraform plan  -var-file user.tfvars
Success! The configuration is valid.

tls_private_key.example: Refreshing state... [id=88bf4602d7a1b0bb68caa75b0429af950a994dd0]
local_sensitive_file.pem_file: Refreshing state... [id=1b5c2f3c975b7ce0329c36837c0ebda9775fd2e7]
data.aws_availability_zones.available: Reading...
aws_key_pair.cortx_key: Refreshing state... [id=devops-key]
aws_eip.elastic_ip: Refreshing state... [id=eipalloc-049c86021b3219e7b]
aws_default_vpc.default: Refreshing state... [id=vpc-b3c13bd8]
data.aws_ami.centos: Reading...
aws_security_group.cortx_deploy: Refreshing state... [id=sg-04d364627c6dc9159]
data.aws_availability_zones.available: Read complete after 1s [id=ap-south-1]
aws_ebs_volume.data_vol[8]: Refreshing state... [id=vol-0cac51df334dcd8ad]
aws_ebs_volume.data_vol[4]: Refreshing state... [id=vol-0d62ed087190811fc]
aws_ebs_volume.data_vol[0]: Refreshing state... [id=vol-04bf011a2667dc99e]
aws_ebs_volume.data_vol[1]: Refreshing state... [id=vol-0655f526d7985133f]
aws_ebs_volume.data_vol[2]: Refreshing state... [id=vol-0c2c74c37d19b6cb6]
aws_ebs_volume.data_vol[7]: Refreshing state... [id=vol-0ed96884a57e85484]
aws_ebs_volume.data_vol[5]: Refreshing state... [id=vol-0b0baec7531140607]
aws_ebs_volume.data_vol[3]: Refreshing state... [id=vol-0a0a77d1ea96e9047]
data.aws_ami.centos: Read complete after 1s [id=ami-0ffc7af9c06de0077]
aws_ebs_volume.data_vol[6]: Refreshing state... [id=vol-05f32b2193bb0c1be]
aws_default_subnet.default: Refreshing state... [id=subnet-02c7645e770270cc0]
aws_instance.cortx_deploy: Refreshing state... [id=i-06f88fcd228dc42f2]
aws_eip_association.eip_assoc: Refreshing state... [id=eipassoc-07fd883836387d549]
aws_network_interface.network_interface_2: Refreshing state... [id=eni-0f0738a1e1eac5ef0]
aws_volume_attachment.deploy_server_data[2]: Refreshing state... [id=vai-3095569191]
aws_volume_attachment.deploy_server_data[5]: Refreshing state... [id=vai-977623988]
aws_volume_attachment.deploy_server_data[8]: Refreshing state... [id=vai-2760976399]
aws_volume_attachment.deploy_server_data[3]: Refreshing state... [id=vai-496156656]
aws_volume_attachment.deploy_server_data[7]: Refreshing state... [id=vai-444335612]
aws_volume_attachment.deploy_server_data[6]: Refreshing state... [id=vai-2216226896]
aws_volume_attachment.deploy_server_data[0]: Refreshing state... [id=vai-3461033653]
aws_network_interface.network_interface_1: Refreshing state... [id=eni-0354447bc07a12087]
aws_volume_attachment.deploy_server_data[1]: Refreshing state... [id=vai-3815717153]
aws_volume_attachment.deploy_server_data[4]: Refreshing state... [id=vai-1215594550]

**Review by shailesh-vaidya — APPROVED** [review]

**Pull request merged**
