### PR TITLE
CORTX-34145: Reduce CORTX container build time

### PR DESCRIPTION
**Pull request by shailesh-vaidya**
# Problem Statement
- Reduced CORTX container image build time using below 
  - Removed `cortx-all` image generation as it's no more used. 
  - Enabled DOCKER_BUILDKIT 
  - Build time is reduced from around 5min to 3min 40 sec

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
- [x] Jenkins pipelines used for testing - 
        -  Custom CI - https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/7807/
        -  Image Generation - https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/cortx-all-docker-image/2535/console

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] Jira ID/ COMMUNITY is prefixed in PR title
      Prefix Syntax - 
        `CORTX-<5 digit JIRA ID>: <PR Title>` - for Seagate Employees
        `COMMUNITY: <PR Title>`  - for open source contributors
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by gauravchaudhari02** [comment]
@shailesh-vaidya, PR looks good. but as we are removing cortx-all reference, can we remove these variables as well?
https://github.com/Seagate/cortx-re/search?p=2&q=env.cortx_all_image

**Comment by shailesh-vaidya** [comment]
> @shailesh-vaidya, PR looks good. but as we are removing cortx-all reference, can we remove these variables as well? https://github.com/Seagate/cortx-re/search?p=2&q=env.cortx_all_image

Sure. I will update the variable name to `env.cortx_images`

**Comment by shailesh-vaidya** [comment]
> > @shailesh-vaidya, PR looks good. but as we are removing cortx-all reference, can we remove these variables as well? https://github.com/Seagate/cortx-re/search?p=2&q=env.cortx_all_image
> 
> Sure. I will update the variable name to `env.cortx_images`

@gauravchaudhari02 - Fixed reference from the `generic` folder. I will raise a separate PR to remove all `centos-7.9.2009` and `centos-7.8.2003` folders as they are not in use now.

**Comment by shailesh-vaidya** [comment]
> > > @shailesh-vaidya, PR looks good. but as we are removing cortx-all reference, can we remove these variables as well? https://github.com/Seagate/cortx-re/search?p=2&q=env.cortx_all_image
> > 
> > 
> > Sure. I will update the variable name to `env.cortx_images`
> 
> @gauravchaudhari02 - Fixed reference from the `generic` folder. I will raise a separate PR to remove all `centos-7.9.2009` and `centos-7.8.2003` folders as they are not in use now.

@gauravchaudhari02 - Raised https://github.com/Seagate/cortx-re/pull/1223 to remove old code.

**Review by pankajgborole — APPROVED** [review]
Approved removal of cortx-all image references

**Comment by gauravchaudhari02** [comment]
@shailesh-vaidya, can we rename this variable as well?
https://github.com/Seagate/cortx-re/blob/9a933717d8419a46191c510d4c37178e9bf44bce/jenkins/custom-ci/generic/custom-ci.groovy#L502
https://github.com/Seagate/cortx-re/blob/9a933717d8419a46191c510d4c37178e9bf44bce/jenkins/custom-ci/generic/custom-ci.groovy#L491
https://github.com/Seagate/cortx-re/blob/9a933717d8419a46191c510d4c37178e9bf44bce/jenkins/custom-ci/generic/custom-ci.groovy#L519
and check running custom-ci with mail template?

**Comment by shailesh-vaidya** [comment]
> @shailesh-vaidya, can we rename this variable as well?
> 
> https://github.com/Seagate/cortx-re/blob/9a933717d8419a46191c510d4c37178e9bf44bce/jenkins/custom-ci/generic/custom-ci.groovy#L502
> 
> 
> https://github.com/Seagate/cortx-re/blob/9a933717d8419a46191c510d4c37178e9bf44bce/jenkins/custom-ci/generic/custom-ci.groovy#L491
> 
> 
> https://github.com/Seagate/cortx-re/blob/9a933717d8419a46191c510d4c37178e9bf44bce/jenkins/custom-ci/generic/custom-ci.groovy#L519
> 
> 
> and check running custom-ci with mail template?

@gauravchaudhari02  - Addressed review comments and tested in https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/7813/console

**Review by gauravchaudhari02 — APPROVED** [review]

**Review by pankajgborole — APPROVED** [review]
Approved

**Pull request merged**
