### PR TITLE
CORTX-34303: Add support for v0.13.0

### PR DESCRIPTION
**Pull request by shailesh-vaidya**
# Problem Statement
- Add support for https://github.com/Seagate/cortx-k8s/releases/tag/v0.13.0

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
- [x] Jenkins pipelines used for testing - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/12770/parameters/
- [ ] Manually triggered Nightly Deployment success with v0.13.0 support - https://eos-jenkins.colo.seagate.com/job/Cortx-Deployment/job/Nightly-K8s-Deploy/954/ 

image

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] Jira ID/ COMMUNITY is prefixed in PR title
      Prefix Syntax - 
        `CORTX-<5 digit JIRA ID>: <PR Title>` - for Seagate Employees
        `COMMUNITY: <PR Title>`  - for open source contributors
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by gauravchaudhari02** [comment]
looks like we need to change version in more files as given in search
https://github.com/Seagate/cortx-re/search?q=v0.12.0

**Comment by shailesh-vaidya** [comment]
> looks like we need to change version in more files as given in search https://github.com/Seagate/cortx-re/search?q=v0.12.0

Done. Please review again.

**Comment by gauravchaudhari02** [comment]
@shailesh-vaidya, below file need chage as well right?
https://github.com/Seagate/cortx-re/blob/b3b7de39201b450fa765445b506028522508c64b/solutions/community-deploy/CORTX-Deployment.md

**Comment by shailesh-vaidya** [comment]
> @shailesh-vaidya, below file need chage as well right? https://github.com/Seagate/cortx-re/blob/b3b7de39201b450fa765445b506028522508c64b/solutions/community-deploy/CORTX-Deployment.md

Done. Please review

**Pull request merged**
