### PR TITLE
CORTX-34384: MendPolicyTest SSPL 

### PR DESCRIPTION
**Pull request by pankajgborole**
Signed-off-by: pankajgborole <pankaj.g.borole@seagate.com>

# Problem Statement
- Adding test code to check Mend policy exception SSPL 

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
- [ ] Jenkins pipelines used for testing

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] Jira ID/ COMMUNITY is prefixed in PR title
      Prefix Syntax - 
        `CORTX-<5 digit JIRA ID>: <PR Title>` - for Seagate Employees
        `COMMUNITY: <PR Title>`  - for open source contributors
- [x] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by shailesh-vaidya** [comment]
@pankajgborole Can we close this pull request

**Comment by shailesh-vaidya** [comment]
@pankajgborole Can we close this pull request

**Comment by pankajgborole** [comment]
> @pankajgborole Can we close this pull request

@shailesh-vaidya  Yes we can close this, no updates planned for mend configuration planned for current repositories.

**Comment by shailesh-vaidya** [comment]
No further activity is planned on this. Marking pull request as closed.

**Pull request closed without merging**
