### PR TITLE
Remove archived repos from Alex report

### PR DESCRIPTION
**Pull request by mukul-seagate11**
Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>

# Problem Statement
- Remove archived repos from Alex report

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
- [ ] Jenkins pipelines used for testing

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by mukul-seagate11** [comment]
raised below repos to remove the Alex workflow from respective repos which will be archived as,

https://github.com/Seagate/cortx-management-portal/pull/637
https://github.com/Seagate/cortx-monitor/pull/540

**Comment by mukul-seagate11** [comment]
@gatekeepers, please approve & merge the PR

**Review by shailesh-vaidya — COMMENTED** [review]
@mukul-seagate11  I see that this change is only changing email configuration. Could you please confirm if any other change is required? 
@venkuppu-chn, @subhalaxmisa  - Could you please review this request. 

Also please fill in details in the PR checklist and add Jira-ID in the PR title.

**Comment by venkuppu-chn** [comment]
@mukul-seagate11 you may close this PR. I have addressed it in https://github.com/Seagate/cortx-re/pull/1016

CC: @shailesh-vaidya

**Pull request closed without merging**
