### PR TITLE
CORTX-33872: RGW: Adding versioning & tagging test cases to nightly s3-tests ceph & splunk test suite job

### PR DESCRIPTION
**Pull request by sachitanands**
# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [x] Unit and System Tests are added
- [x] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [x] Testing was performed with RPM
- [x] Jenkins pipelines used for testing

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [x] Interface change (if any) are documented
- [x] Side effects on other features (deployment/upgrade)
- [x] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [x] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by sachitanands** [comment]
Triggered these automation jobs with latest test cases,
  **Splunk** : https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Splunk-RGW/150/ 
  **Ceph**  :

**Comment by sachitanands** [comment]
Triggered : https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Ceph-RGW/192/

**Review by kapiljinna — APPROVED** [review]
Approved

**Review by shriya-deshmukh — APPROVED** [review]

**Review by cdeshmukh — APPROVED** [review]

**Comment by cdeshmukh** [comment]
@shailesh-vaidya @kapiljinna can you please review and merge this

**Review by shailesh-vaidya — APPROVED** [review]

**Review by shailesh-vaidya — COMMENTED** [review]
@sachitanands Can you please fill PR template details.

**Comment by sachitanands** [comment]
> @sachitanands Can you please fill PR template details.

done. once 1 Node is passed, we can merge this PR.

**Pull request merged**
