### PR TITLE
CORTX-32961 : Update changelog file extension and info message

### PR DESCRIPTION
**Pull request by gauravchaudhari02**
Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@seagate.com>

# Problem Statement
- Release has `.txt` extension for changelog which is now changed to `.md`

# Design
-  Change file extension to `.md`

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [x] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
- [x] Jenkins pipelines used for testing
   https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/gc-space/job/changelog-test/25/

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Review by pankajgborole — APPROVED** [review]
Approved changes to update CHANGESET.md

**Review by shailesh-vaidya — COMMENTED** [review]
Can you please add Jenkins job used for testing 
Please fill PR template details.

**Comment by gauravchaudhari02** [comment]
@shailesh-vaidya, did not test release, nightly jobs as they do not have input parameter for custom repository, but tested changelog changes - https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/gc-space/job/changelog-test/25/

**Review by pankajgborole — APPROVED** [review]
Approved

**Pull request merged**
