### PR TITLE
CORTX-34145: Remove orphan codebase from repository

### PR DESCRIPTION
**Pull request by shailesh-vaidya**
# Problem Statement
- We have an old code for CentOS 7.9, 7.8, and RHEL 7.7 support in the repo. This codebase is not used but needs to be maintained for Codacy and other changes. Hence raised this PR to remove the same. 
- We will create a tag before merging this PR to track any issues occurring due to this change. 

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
- [x] Jenkins pipelines used for testing - There is no Jenkinsfile addition but only removal. Hence not tested. 

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] Jira ID/ COMMUNITY is prefixed in PR title
      Prefix Syntax - 
        `CORTX-<5 digit JIRA ID>: <PR Title>` - for Seagate Employees
        `COMMUNITY: <PR Title>`  - for open source contributors
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

-----
[View rendered jenkins/internal-ci/centos-7.8.2003/README.md](https://github.com/shailesh-vaidya/cortx-re/blob/del-orphan-code/jenkins/internal-ci/centos-7.8.2003/README.md)

### CODE REVIEW

**Comment by gauravchaudhari02** [comment]
@shailesh-vaidya, can we remove this as well?
https://github.com/Seagate/cortx-re/tree/main/jenkins/custom-ci/centos-7.9.2009

**Comment by shailesh-vaidya** [comment]
> @shailesh-vaidya, can we remove this as well? https://github.com/Seagate/cortx-re/tree/main/jenkins/custom-ci/centos-7.9.2009

@gauravchaudhari02  Not removing this as Motr team was using https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.9/job/custom-ci/. We need to get confirmation from them before deleting it.  
Waiting for confirmation will add to the delay hence deleting the codebase for which we are absolutely sure.

**Comment by shailesh-vaidya** [comment]
@swanand-gadre  - I am only removing the orphan codebase from the repo in this PR. However, mend check is failing with the below message. Could you please check. 


image

**Review by gauravchaudhari02 — APPROVED** [review]

**Comment by swanand-gadre** [comment]
> @swanand-gadre - I am only removing the orphan codebase from the repo in this PR. However, mend check is failing with the below message. Could you please check.
> 
> image

Hi @shailesh-vaidya 

numpy and urllib3 are at the most recent level possible with the current configuration.
For the higher versions, python needs upgrade.

If check is failing because of Mend, then it needs exception for these 2 packages.

**Pull request merged**
