### PR TITLE
CORTX-34406: Update NFS mount 

### PR DESCRIPTION
**Pull request by gauravchaudhari02**
# Problem Statement
- Shifted NFS to new server

# Design
-  Change artifacts access links from old NFS to new NFS 

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
- [ ] Jenkins pipelines used for testing

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] Jira ID/ COMMUNITY is prefixed in PR title
      Prefix Syntax - 
        `CORTX-<5 digit JIRA ID>: <PR Title>` - for Seagate Employees
        `COMMUNITY: <PR Title>`  - for open source contributors
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [x] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by gauravchaudhari02** [comment]
**Status for Changed files -**

**Groovy Files**
jenkins/automation/changelog-generation.groovy - https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/Cortx-Automation/job/changelog-generation/784/
jenkins/automation/rgw/ceph/ceph-build-docker.groovy - Job is running on Nitish's fork
jenkins/automation/rgw/ceph/ceph-build-vm.groovy - Job is running on Nitish's fork
jenkins/custom-ci/generic/cortx-cc.groovy - https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/ 
jenkins/custom-ci/generic/cortx-ha.groovy
jenkins/custom-ci/generic/csm-agent.groovy
jenkins/custom-ci/generic/custom-ci.groovy
jenkins/custom-ci/generic/hare.groovy
jenkins/custom-ci/generic/motr.groovy
jenkins/internal-ci/generic/branch/cortx-cc.groovy - https://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/rockylinux-8.4/
jenkins/internal-ci/generic/branch/cortx-ha.groovy
jenkins/internal-ci/generic/branch/cortx-py-utils.groovy
jenkins/internal-ci/generic/branch/cortx-rgw-integration.groovy
jenkins/internal-ci/generic/branch/cortx-rgw.groovy
jenkins/internal-ci/generic/branch/csm-agent.groovy
jenkins/internal-ci/generic/branch/hare.groovy
jenkins/internal-ci/generic/branch/motr.groovy
jenkins/internal-ci/generic/branch/provisioner.groovy
jenkins/internal-ci/generic/branch/release.groovy
jenkins/internal-ci/generic/pr/cortx_deployment/cortx-rgw-integration.groovy - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/ 
jenkins/internal-ci/generic/pr/cortx_deployment/cortx-rgw.groovy
jenkins/internal-ci/generic/pr/cortx_deployment/csm-agent.groovy
jenkins/internal-ci/generic/pr/cortx_deployment/ha.groovy
jenkins/internal-ci/generic/pr/cortx_deployment/hare.groovy
jenkins/internal-ci/generic/pr/cortx_deployment/motr.groovy
jenkins/internal-ci/generic/pr/cortx_deployment/provisioner.groovy
jenkins/internal-ci/generic/pr/cortx_deployment/pyutils.groovy

**----------------------------------------------------------------------------------------------**
Jobs older than 6 months (Not tested)

jenkins/custom-ci/centos-7.9.2009/cortx-ha.groovy
jenkins/custom-ci/centos-7.9.2009/csm-agent.groovy
jenkins/custom-ci/centos-7.9.2009/csm-web.groovy
jenkins/custom-ci/centos-7.9.2009/custom-ci.groovy
jenkins/custom-ci/centos-7.9.2009/hare.groovy
jenkins/custom-ci/centos-7.9.2009/s3server.groovy
jenkins/deployment/vm_deployment/cortx_stack/cortx_deploy_vm_1n.groovy
jenkins/deployment/vm_deployment/cortx_stack/cortx_deploy_vm_3n.groovy
jenkins/deployment/vm_deployment/cortx_stack/cortx_factory_deploy_vm_1n.groovy
jenkins/deployment/vm_deployment/cortx_stack/cortx_factory_deploy_vm_3n.groovy
jenkins/deployment/vm_deployment/mini_provisioner/cortx_stack_no_ha.groovy
jenkins/deployment/vm_deployment/mini_provisioner/hare.groovy
jenkins/deployment/vm_deployment/mini_provisioner/motr.groovy
jenkins/deployment/vm_deployment/mini_provisioner/pyutils.groovy
jenkins/deployment/vm_deployment/mini_provisioner/s3server.groovy
jenkins/opensource-ci/ova-build/csm-web-ova-build.groovy
jenkins/opensource-ci/ova-build/ova-release.groovy
jenkins/automation/rgw/cortx-rgw-build.groovy
jenkins/performance-ci/performance-check.groovy
jenkins/automation/nightly.groovy
jenkins/automation/kubernetes/symas-openldap.groovy
jenkins/automation/kubernetes/k8-custom-ci.groovy
jenkins/automation/alert.groovy

---------------------------------------------------------------------------------------------------

**Scripts**
docker/cortx-deploy/build.sh - https://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/rockylinux-8.4/job/cortx-docker-images/1116/
docker/cortx-deploy/docker-compose.yml - https://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/rockylinux-8.4/job/cortx-docker-images/1116/
solutions/vmware/migration/ansible/vm-metadata-operations/roles/setup_prerequisites/tasks/setup_nfs_mount.yml - Tested by running ansible-playbook on local environment

**--------------------------------------------------------------------------------------------------------------**
Deprecated Scripts

scripts/deployment/roles/hw_deployment/vars/config.yml
scripts/mini_provisioner/roles/csm/tasks/01_install_prerequisites.yml
scripts/mini_provisioner/roles/hare/tasks/01_install_prerequisites.yml
scripts/mini_provisioner/roles/hare/templates/cortx.repo.j2
scripts/mini_provisioner/roles/motr/tasks/01_install_prerequisites.yml
scripts/mini_provisioner/roles/pyutils/tasks/01_install_prerequisites.yml
scripts/mini_provisioner/roles/s3server/tasks/01_install_prerequisites.yml
scripts/mini_provisioner/roles/s3server/templates/cortx.repo.j2
scripts/mini_provisioner/roles/s3server/vars/config.yml
scripts/mini_provisioner/roles/sspl/tasks/01_install_prerequisites.yml
scripts/performance/_run-performace-tests-functions.sh
jenkins/deployment/hw_deployment/hw_deployment
jenkins/deployment/ova_release
scripts/build-retention/README.md
scripts/build-retention/cleanup.sh
scripts/build-retention/monitoring/alert.rules
scripts/build-retention/monitoring/docker-compose.yml
scripts/release_support/ova-release-notes/ova_release.py
scripts/security/whitesource_container_scan_function.sh
scripts/cortx_metarpm/build-release-metarpm.sh
scripts/release_support/build_readme.sh
scripts/release_support/rpm-validator.sh
scripts/third-party-rpm/install-cortx-prereq.sh
solutions/kubernetes/ceph-binary-build.sh
solutions/kubernetes/ceph-deploy-functions.sh

**Comment by shailesh-vaidya** [comment]
> **Status for Changed files -**
> 
> **Groovy Files** jenkins/automation/changelog-generation.groovy - https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/Cortx-Automation/job/changelog-generation/784/ jenkins/automation/rgw/ceph/ceph-build-docker.groovy - Job is running on Nitish's fork jenkins/automation/rgw/ceph/ceph-build-vm.groovy - Job is running on Nitish's fork jenkins/custom-ci/generic/cortx-cc.groovy - https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/ jenkins/custom-ci/generic/cortx-ha.groovy jenkins/custom-ci/generic/csm-agent.groovy jenkins/custom-ci/generic/custom-ci.groovy jenkins/custom-ci/generic/hare.groovy jenkins/custom-ci/generic/motr.groovy jenkins/internal-ci/generic/branch/cortx-cc.groovy - https://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/rockylinux-8.4/ jenkins/internal-ci/generic/branch/cortx-ha.groovy jenkins/internal-ci/generic/branch/cortx-py-utils.groovy jenkins/internal-ci/generic/branch/cortx-rgw-integration.groovy jenkins/internal-ci/generic/branch/cortx-rgw.groovy jenkins/internal-ci/generic/branch/csm-agent.groovy jenkins/internal-ci/generic/branch/hare.groovy jenkins/internal-ci/generic/branch/motr.groovy jenkins/internal-ci/generic/branch/provisioner.groovy jenkins/internal-ci/generic/branch/release.groovy jenkins/internal-ci/generic/pr/cortx_deployment/cortx-rgw-integration.groovy - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/ jenkins/internal-ci/generic/pr/cortx_deployment/cortx-rgw.groovy jenkins/internal-ci/generic/pr/cortx_deployment/csm-agent.groovy jenkins/internal-ci/generic/pr/cortx_deployment/ha.groovy jenkins/internal-ci/generic/pr/cortx_deployment/hare.groovy jenkins/internal-ci/generic/pr/cortx_deployment/motr.groovy jenkins/internal-ci/generic/pr/cortx_deployment/provisioner.groovy jenkins/internal-ci/generic/pr/cortx_deployment/pyutils.groovy
> 
> **----------------------------------------------------------------------------------------------** Jobs older than 6 months
> 
> jenkins/custom-ci/centos-7.9.2009/cortx-ha.groovy jenkins/custom-ci/centos-7.9.2009/csm-agent.groovy jenkins/custom-ci/centos-7.9.2009/csm-web.groovy jenkins/custom-ci/centos-7.9.2009/custom-ci.groovy jenkins/custom-ci/centos-7.9.2009/hare.groovy jenkins/custom-ci/centos-7.9.2009/s3server.groovy jenkins/deployment/vm_deployment/cortx_stack/cortx_deploy_vm_1n.groovy jenkins/deployment/vm_deployment/cortx_stack/cortx_deploy_vm_3n.groovy jenkins/deployment/vm_deployment/cortx_stack/cortx_factory_deploy_vm_1n.groovy jenkins/deployment/vm_deployment/cortx_stack/cortx_factory_deploy_vm_3n.groovy jenkins/deployment/vm_deployment/mini_provisioner/cortx_stack_no_ha.groovy jenkins/deployment/vm_deployment/mini_provisioner/hare.groovy jenkins/deployment/vm_deployment/mini_provisioner/motr.groovy jenkins/deployment/vm_deployment/mini_provisioner/pyutils.groovy jenkins/deployment/vm_deployment/mini_provisioner/s3server.groovy jenkins/opensource-ci/ova-build/csm-web-ova-build.groovy jenkins/opensource-ci/ova-build/ova-release.groovy jenkins/automation/rgw/cortx-rgw-build.groovy jenkins/performance-ci/performance-check.groovy jenkins/automation/nightly.groovy jenkins/automation/kubernetes/symas-openldap.groovy jenkins/automation/kubernetes/k8-custom-ci.groovy jenkins/automation/alert.groovy
> 
> **Scripts** docker/cortx-deploy/build.sh - https://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/rockylinux-8.4/job/cortx-docker-images/1116/ docker/cortx-deploy/docker-compose.yml - https://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/rockylinux-8.4/job/cortx-docker-images/1116/ solutions/vmware/migration/ansible/vm-metadata-operations/roles/setup_prerequisites/tasks/setup_nfs_mount.yml - Tested by running ansible-playbook on local environment
> 
> **----------------------------------------------------------------------------------------------** Deprecated Scripts
> 
> scripts/deployment/roles/hw_deployment/vars/config.yml scripts/mini_provisioner/roles/csm/tasks/01_install_prerequisites.yml scripts/mini_provisioner/roles/hare/tasks/01_install_prerequisites.yml scripts/mini_provisioner/roles/hare/templates/cortx.repo.j2 scripts/mini_provisioner/roles/motr/tasks/01_install_prerequisites.yml scripts/mini_provisioner/roles/pyutils/tasks/01_install_prerequisites.yml scripts/mini_provisioner/roles/s3server/tasks/01_install_prerequisites.yml scripts/mini_provisioner/roles/s3server/templates/cortx.repo.j2 scripts/mini_provisioner/roles/s3server/vars/config.yml scripts/mini_provisioner/roles/sspl/tasks/01_install_prerequisites.yml scripts/performance/_run-performace-tests-functions.sh jenkins/deployment/hw_deployment/hw_deployment jenkins/deployment/ova_release scripts/build-retention/README.md scripts/build-retention/cleanup.sh scripts/build-retention/monitoring/alert.rules scripts/build-retention/monitoring/docker-compose.yml scripts/release_support/ova-release-notes/ova_release.py scripts/security/whitesource_container_scan_function.sh scripts/cortx_metarpm/build-release-metarpm.sh scripts/release_support/build_readme.sh scripts/release_support/rpm-validator.sh scripts/third-party-rpm/install-cortx-prereq.sh solutions/kubernetes/ceph-binary-build.sh solutions/kubernetes/ceph-deploy-functions.sh

@gauravchaudhari02 - Can we get this code in `main` branch of Seagate repo. 
```bash
jenkins/automation/rgw/ceph/ceph-build-docker.groovy - Job is running on Nitish's fork
jenkins/automation/rgw/ceph/ceph-build-vm.groovy - Job is running on Nitish's fork
```

**Review by shailesh-vaidya — COMMENTED** [review]
Changes looks good to me.

**Review by pankajgborole — APPROVED** [review]
Approved 
Changes looks good

**Comment by shailesh-vaidya** [comment]
> > **Status for Changed files -**
> > **Groovy Files** jenkins/automation/changelog-generation.groovy - https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/Cortx-Automation/job/changelog-generation/784/ jenkins/automation/rgw/ceph/ceph-build-docker.groovy - Job is running on Nitish's fork jenkins/automation/rgw/ceph/ceph-build-vm.groovy - Job is running on Nitish's fork jenkins/custom-ci/generic/cortx-cc.groovy - https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/ jenkins/custom-ci/generic/cortx-ha.groovy jenkins/custom-ci/generic/csm-agent.groovy jenkins/custom-ci/generic/custom-ci.groovy jenkins/custom-ci/generic/hare.groovy jenkins/custom-ci/generic/motr.groovy jenkins/internal-ci/generic/branch/cortx-cc.groovy - https://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/rockylinux-8.4/ jenkins/internal-ci/generic/branch/cortx-ha.groovy jenkins/internal-ci/generic/branch/cortx-py-utils.groovy jenkins/internal-ci/generic/branch/cortx-rgw-integration.groovy jenkins/internal-ci/generic/branch/cortx-rgw.groovy jenkins/internal-ci/generic/branch/csm-agent.groovy jenkins/internal-ci/generic/branch/hare.groovy jenkins/internal-ci/generic/branch/motr.groovy jenkins/internal-ci/generic/branch/provisioner.groovy jenkins/internal-ci/generic/branch/release.groovy jenkins/internal-ci/generic/pr/cortx_deployment/cortx-rgw-integration.groovy - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/ jenkins/internal-ci/generic/pr/cortx_deployment/cortx-rgw.groovy jenkins/internal-ci/generic/pr/cortx_deployment/csm-agent.groovy jenkins/internal-ci/generic/pr/cortx_deployment/ha.groovy jenkins/internal-ci/generic/pr/cortx_deployment/hare.groovy jenkins/internal-ci/generic/pr/cortx_deployment/motr.groovy jenkins/internal-ci/generic/pr/cortx_deployment/provisioner.groovy jenkins/internal-ci/generic/pr/cortx_deployment/pyutils.groovy
> > **----------------------------------------------------------------------------------------------** Jobs older than 6 months
> > jenkins/custom-ci/centos-7.9.2009/cortx-ha.groovy jenkins/custom-ci/centos-7.9.2009/csm-agent.groovy jenkins/custom-ci/centos-7.9.2009/csm-web.groovy jenkins/custom-ci/centos-7.9.2009/custom-ci.groovy jenkins/custom-ci/centos-7.9.2009/hare.groovy jenkins/custom-ci/centos-7.9.2009/s3server.groovy jenkins/deployment/vm_deployment/cortx_stack/cortx_deploy_vm_1n.groovy jenkins/deployment/vm_deployment/cortx_stack/cortx_deploy_vm_3n.groovy jenkins/deployment/vm_deployment/cortx_stack/cortx_factory_deploy_vm_1n.groovy jenkins/deployment/vm_deployment/cortx_stack/cortx_factory_deploy_vm_3n.groovy jenkins/deployment/vm_deployment/mini_provisioner/cortx_stack_no_ha.groovy jenkins/deployment/vm_deployment/mini_provisioner/hare.groovy jenkins/deployment/vm_deployment/mini_provisioner/motr.groovy jenkins/deployment/vm_deployment/mini_provisioner/pyutils.groovy jenkins/deployment/vm_deployment/mini_provisioner/s3server.groovy jenkins/opensource-ci/ova-build/csm-web-ova-build.groovy jenkins/opensource-ci/ova-build/ova-release.groovy jenkins/automation/rgw/cortx-rgw-build.groovy jenkins/performance-ci/performance-check.groovy jenkins/automation/nightly.groovy jenkins/automation/kubernetes/symas-openldap.groovy jenkins/automation/kubernetes/k8-custom-ci.groovy jenkins/automation/alert.groovy
> > **Scripts** docker/cortx-deploy/build.sh - https://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/rockylinux-8.4/job/cortx-docker-images/1116/ docker/cortx-deploy/docker-compose.yml - https://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/rockylinux-8.4/job/cortx-docker-images/1116/ solutions/vmware/migration/ansible/vm-metadata-operations/roles/setup_prerequisites/tasks/setup_nfs_mount.yml - Tested by running ansible-playbook on local environment
> > **----------------------------------------------------------------------------------------------** Deprecated Scripts
> > scripts/deployment/roles/hw_deployment/vars/config.yml scripts/mini_provisioner/roles/csm/tasks/01_install_prerequisites.yml scripts/mini_provisioner/roles/hare/tasks/01_install_prerequisites.yml scripts/mini_provisioner/roles/hare/templates/cortx.repo.j2 scripts/mini_provisioner/roles/motr/tasks/01_install_prerequisites.yml scripts/mini_provisioner/roles/pyutils/tasks/01_install_prerequisites.yml scripts/mini_provisioner/roles/s3server/tasks/01_install_prerequisites.yml scripts/mini_provisioner/roles/s3server/templates/cortx.repo.j2 scripts/mini_provisioner/roles/s3server/vars/config.yml scripts/mini_provisioner/roles/sspl/tasks/01_install_prerequisites.yml scripts/performance/_run-performace-tests-functions.sh jenkins/deployment/hw_deployment/hw_deployment jenkins/deployment/ova_release scripts/build-retention/README.md scripts/build-retention/cleanup.sh scripts/build-retention/monitoring/alert.rules scripts/build-retention/monitoring/docker-compose.yml scripts/release_support/ova-release-notes/ova_release.py scripts/security/whitesource_container_scan_function.sh scripts/cortx_metarpm/build-release-metarpm.sh scripts/release_support/build_readme.sh scripts/release_support/rpm-validator.sh scripts/third-party-rpm/install-cortx-prereq.sh solutions/kubernetes/ceph-binary-build.sh solutions/kubernetes/ceph-deploy-functions.sh
> 
> @gauravchaudhari02 - Can we get this code in `main` branch of Seagate repo.
> 
> ```shell
> jenkins/automation/rgw/ceph/ceph-build-docker.groovy - Job is running on Nitish's fork
> jenkins/automation/rgw/ceph/ceph-build-vm.groovy - Job is running on Nitish's fork
> ```

@gauravchaudhari02 Created https://github.com/Seagate/cortx-re/pull/1289 for this.

**Review by shailesh-vaidya — APPROVED** [review]

**Pull request merged**
