### PR TITLE
CORTX-33539_addition_of_newtcs_in_sanityscript.

### PR DESCRIPTION
**Pull request by Naveen-Kumar-seagate**
Signed-off-by: root <root@ssc-vm-g2-rhev4-3400.colo.seagate.com>

# Problem Statement
- Adding tests to Iosanity.sh script for sanity test.
  All tests running using aws s3api .
-Listbucket
-Head bucket
-Get object
-Head bucket
-Deleteobject
-Bulk delete
-Copy Object

# Design
-  https://jts.seagate.com/browse/CORTX-33539

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-Tested the changes and ran through jenkins job here is the link for console output
 https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/9263/console

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Review by shailesh-vaidya — CHANGES_REQUESTED** [review]
@Naveen-Kumar-seagate  - Thanks for adding test cases. In order to merge this PR

- Please update the PR title with Jira details
- Please fill in the PR template
- Please test changes with Jenkins job and add its link.

**Review by shailesh-vaidya — APPROVED** [review]
Validated with - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/9351/console

**Comment by gauravchaudhari02** [comment]
@shailesh-vaidya, looks like sign is not good. it is with root user and vm name. should we change it?

**Comment by shailesh-vaidya** [comment]
> @shailesh-vaidya, looks like sign is not good. it is with root user and vm name. should we change it?

@Naveen-Kumar-seagate  Seems you have committed change using the root user only. Can you please correct it? 

image

**Comment by Naveen-Kumar-seagate** [comment]
Created New Pr

**Pull request closed without merging**
